YNOR0573-174: Add new service to get information from Contact table
YCloudYUSA/openy_traction_rec pull request #20
Opened 2024-11-27 05:41 UTC by szherebchuk

2024-11-27 12:30 UTC, anpolimus requested changes

2024-11-27 12:30 UTC, anpolimus commented on src/TractionRecUserMembership.php
> +      $result = $this->tractionRecClient->executeQuery("SELECT Id,
@szherebchuk please, add possibility to alter this query by another modules. List of fields is dedicated to our client. We have to add ability to change it for other projects.

2024-11-27 12:35 UTC, mkdok commented on src/TractionRecUserMembership.php
> +   * {@inheritdoc}
The class doesn't extend or implement any class/interface. Please use interface implementation OR define proper method annotation.

2024-11-27 12:36 UTC, mkdok commented on src/TractionRecUserMembership.php
> +   * {@inheritdoc}
The same: wrong method annotation/comment.

2024-12-05 14:51 UTC, anpolimus approved these changes

2024-12-05 15:28 UTC, merged