docs: Update Salesforce instructions
YCloudYUSA/openy_traction_rec pull request #9
Opened 2024-06-19 15:40 UTC by froboy

2024-06-20 21:00 UTC, anpolimus requested changes

2024-06-20 21:00 UTC, anpolimus commented on README.md
> +     - Assign the User to the **Profile** you created above, or a **Permission Set** that has the [necessary permissions](#salesforce-permissions).
Can we add a comment, that you have to create a new user always to assign it to the profile?

2024-06-20 21:00 UTC, anpolimus commented on README.md
> +     - **User License** - Salesforce Platform
When I select it, I cant select Profile that I've created for the app.
Profile field is dependent on User License. Maybe we have to skip this rule and use default one that Traction Rec offers

2024-06-20 21:04 UTC, anpolimus commented on README.md
> +   - Go to **Setup** > **Connected Apps** > **Manage Connected Apps** and choose your new app. Assign the **Profile** or **Permission Set** that contains your new user if it does not already show und
```suggestion
   - Go to **Setup** > **Apps** > **Connected Apps** > **Manage Connected Apps** and choose your new app. Assign the **Profile** or **Permission Set** that contains your new user if it does not already show under the relevant section.
```

2024-06-26 15:54 UTC, froboy commented on README.md
> +   - When asked what **Existing Profile** to clone from, select **Standard Platform User**.
```suggestion
   - When asked what **Existing Profile** to clone from, select **Standard User** or **Standard Platform User**. Be sure to note the **User License** connected to the target profile.
```

2024-06-26 15:54 UTC, froboy commented on README.md
> +     - **User License** - Salesforce Platform
```suggestion
     - **User License** - The option under which you created the Profile in the previous step.
```

2024-06-26 15:54 UTC, froboy commented on README.md
> +     - Assign the User to the **Profile** you created above, or a **Permission Set** that has the [necessary permissions](#salesforce-permissions).
https://github.com/YCloudYUSA/openy_traction_rec/pull/9/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R60

>    - You **must** do this **before** creating a user. Alternatively, existing users can be assigned a **Permision Set**. Instructions TBD.

Does line 60 cover that?

2024-06-26 16:01 UTC, froboy commented
@anpolimus pushing these for now. I'll have a new PR soon if you have more comments.

2024-06-26 16:01 UTC, merged